site_name: Yinshi Documentation
site_description: Documentation du projet Yinshi (vue via md2html)

# On laisse MkDocs lire directement les fichiers de Yinshi
# sans modifier le repo Yinshi lui-même.
docs_dir: ../yinshi/docs

# Thème Material pour une interface moderne
theme:
  name: material

# IMPORTANT : pas de section `nav` -> MkDocs génère la navigation
# automatiquement à partir de l’arborescence disque.
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
